Location.create(name: "Kitchen")
Location.create(name: "Bedroom")
Location.create(name: "Pantry")
Location.create(name: "Living Room")
Location.create(name: "Garage")
Location.create(name: "Attic")
Location.create(name: "Basement")
Location.create(name: "Bathroom")

Type.create(name: "Clothing")
Type.create(name: "Food")
Type.create(name: "Household Appliance")
Type.create(name: "Book")
Type.create(name: "DVD")
Type.create(name: "Blu-ray")
Type.create(name: "Furniture")
Type.create(name: "Houseplant")
Type.create(name: "Decorative")
Type.create(name: "Jewelry")
Type.create(name: "Tool")
Type.create(name: "Bedding")
Type.create(name: "Toy")
Type.create(name: "Computer")
